# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  name: default

steps:
- script: |
    # Update package lists and install prerequisites
    sudo apt-get update
    sudo apt-get install -y software-properties-common

    # Add Ondrej PHP PPA
    sudo add-apt-repository -y ppa:ondrej/php
    sudo apt-get update

    # Install PHP 7.2 and common packages
    sudo apt-get install -y php7.2 php7.2-cli php7.2-common php7.2-dev
    php -v
  displayName: 'Install PHP 7.2 from PPA'

- script: |
    sudo update-alternatives --install /usr/bin/php php /usr/bin/php7.2 1
    sudo update-alternatives --install /usr/bin/phar phar /usr/bin/phar7.2 1
    sudo update-alternatives --install /usr/bin/phpdbg phpdbg /usr/bin/phpdbg7.2 1
    sudo update-alternatives --install /usr/bin/php-cgi php-cgi /usr/bin/php-cgi7.2 1
    sudo update-alternatives --install /usr/bin/phar.phar phar.phar /usr/bin/phar.phar7.2 1
    sudo update-alternatives --set php /usr/bin/php7.2
    sudo update-alternatives --set phar /usr/bin/phar7.2
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg7.2
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi7.2
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.2
    php -v
  displayName: 'Configure PHP version 7.2'

- script: |
    php -v
  displayName: 'Check default PHP version'

- script: |
    # Install Composer
    curl -sS https://getcomposer.org/installer | php
    sudo mv composer.phar /usr/local/bin/composer
    composer --version
  displayName: 'Install Composer'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: |
    # Install zip utility
    sudo apt-get install -y zip
  displayName: 'Install zip utility'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive source code'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'