# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  name: default

steps:
- script: |
    php -v
    which php
    ls -l /usr/bin/php*
  displayName: 'Check PHP installation'

- script: |
    sudo apt-get update
    sudo apt-get install -y php7.2 php7.2-cli php7.2-common php7.2-dev
  displayName: 'Install PHP 7.2'

- script: |
    sudo update-alternatives --install /usr/bin/php php /usr/bin/php7.2 1
    sudo update-alternatives --install /usr/bin/phar phar /usr/bin/phar7.2 1
    sudo update-alternatives --install /usr/bin/phpdbg phpdbg /usr/bin/phpdbg7.2 1
    sudo update-alternatives --install /usr/bin/php-cgi php-cgi /usr/bin/php-cgi7.2 1
    sudo update-alternatives --install /usr/bin/phar.phar phar.phar /usr/bin/phar.phar7.2 1
    sudo update-alternatives --set php /usr/bin/php7.2
    sudo update-alternatives --set phar /usr/bin/phar7.2
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg7.2
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi7.2
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.2
    php -v
  displayName: 'Configure PHP version 7.2'

- script: |
    php -v
  displayName: 'Check default PHP version'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: |
    vendor/bin/phpunit
  displayName: 'Run PHPUnit tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive build artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'